### PR TITLE
Feat: #11 Update URL scripts

### PR DESCRIPTION
**Pull request by vmelikyan**
## Pre-merge checklist

- [ ] All new code is documented with [JSDoc](http://usejsdoc.org/) tags
- [ ] Any changes to the `docs/` directory have been committed
- [x] `npm run test` does not produce any errors

### CODE REVIEW

**Comment by josephwynn-sc** [comment]
Awesome, thanks for submitting this! Will special characters like `\t` and `\n` be interpreted correctly? For example:

```
speedcurve update-url --urlId 1234 --script "setHeader\taccept: text/html\nnavigate\t%URL%"
```

**Comment by vmelikyan** [comment]
> Awesome, thanks for submitting this! Will special characters like `\t` and `\n` be interpreted correctly? For example:
> 
> 
> 
> ```
> 
> speedcurve update-url --urlId 1234 --script "setHeader\taccept: text/html\nnavigate\t%URL%"
> 
> ```

I've tested with `\n` and it worked. I'll double check `\t`

**Comment by vmelikyan** [comment]
@josephwynn-sc quick question, is %URL% a variable of sorts that is the actual URL, or you just used it as a placeholder in your example.

**Comment by vmelikyan** [comment]
> > Awesome, thanks for submitting this! Will special characters like `\t` and `\n` be interpreted correctly? For example:
> > ```
> > 
> > speedcurve update-url --urlId 1234 --script "setHeader\taccept: text/html\nnavigate\t%URL%"
> > ```
> 
> I've tested with `\n` and it worked. I'll double check `\t`

Confirming, both `\t` and `\n` work as expected.

**Comment by josephwynn-sc** [comment]
Sweet, thanks for testing! `%URL%` is a special placeholder supported by WPT scripts, so it is a valid part of the script string.

**Comment by josephwynn-sc** [comment]
Boom, thanks @vmelikyan! I'll bump the version and create a new release later today.

**Comment by josephwynn-sc** [comment]
1.3.0 is out now, which contains this change.

**Pull request merged**
