### PR TITLE
Deep link to most recent deploy comparison for a given siteId

### PR DESCRIPTION
**Pull request by pjlee11**
Opinionated feature that takes a siteId (plus optional params) to deploy synthetic tests for the specified site before waiting for the tests to finish. Upon the deploy finishing it creates a deep link to the most recent two deploys of the specified site. Ideal for creating a post-release comparison deep link for synthetic tests. 

`yarn build && node dist/cli/index.js --key="{API_KEY}" deploy-site-wait-for-deep-link {SITE_ID} --browser "apple-iphone-7" --region "eu-west-2" --deepLinkUrl {DEEP_LINK_URL}`

## Pre-merge checklist
- [ ] Tests added for new feature
- [ ? ] All new code is documented with [JSDoc](http://usejsdoc.org/) tags
- [x] Any changes to the `docs/` directory have been committed
- [x] `npm run test` does not produce any errors

### TODO 
- Add some basic tests
- JSDoc review

### CODE REVIEW

**Comment by pjlee11** [comment]
CC @josephwynn-sc thoughts would be greatly appreciated? 😄

**Comment by josephwynn-sc** [comment]
First thought is I should really automate the docs generation because it makes PRs so big! Maybe don't commit the docs/ directory for now just to make review easier.

Is the use case for this that you want to kick off a deploy and have the CLI output a URL to your deploy dashboard?

**Comment by josephwynn-sc** [comment]
Is `--deepLinkUrl` a URL ID?

**Comment by pjlee11** [comment]
I’ll remove the docs tomorrow (Haven’t got my mac on me) 👍

Yeah that’s pretty much the use case, ideally I want to post a URL to a channel that would prompt people checking the deploy comparison for any performance regressions following a release. 

Yep --deepLinkUrl is a url ID, it needs to be separate from --url because that value is an array specifying which urls to run for the synthetic tests

**Comment by josephwynn-sc** [comment]
Gotcha. I think this feature might be a bit too narrow to justify putting in the CLI, but I can see a case for something similar that's more generic. Since the deploy command knows which sites were deployed, there could be a `--output-dashboard-urls` option or something that gets the URLs in each deployed site and outputs a dashboard URL for each one.

```
$ speedcurve deploy --wait --output-dashboard-urls
Requesting deploys for 2 sites...
✔ Deploy 481513 triggered 6 tests for BBC News
✔ Deploy 481511 triggered 6 tests for The Guardian
Waiting for tests to complete... 12/12 (100%)
Deploy URL for BBC News / Home: https://sc.dev/f7ds8hf38
Deploy URL for BBC News / Article: https://sc.dev/f7ds8hf38
Deploy URL for The Guardian / Home: https://sc.dev/f7ds8hf38
Deploy URL for The Guardian / Article: https://sc.dev/f7ds8hf38
```

Although I can see that getting pretty unwieldy when you have more than a few URLs per site.

And another spanner in the works for getting this merged is that in the next few months we're going to throw away everything to do with deploys in SpeedCurve and start from scratch to take a more CI/CD-oriented approach :see_no_evil:

**Comment by pjlee11** [comment]
Just for clarity the URL I'm after is to the deploy comparisons for an exact site rather than the dashboards...

image

I thought this feature would probably be a little too niche for the CLI but worth opening a PR to discuss. We will probably publish a fork in-house as this ticks a box for now ✅ 

Really interesting to hear about SpeedCurve moving towards a CI/CD-oriented approach, that potentially would naturally integrate with how we're planning on using SpeedCurve in-house in the CI lifecycle 🎉

**Pull request closed without merging**
